origins:
  spell-cooldown: 30
  creeper:
    enabled: true
    spell:
      enabled: true
      power: 4
      fire-damage: false
      destroy-blocks: false
  feline:
    enabled: true
    spell:
      enabled: true
  blaze:
    enabled: true
    spell:
      enabled: true
  vampire:
    enabled: true
    spell:
      enabled: true
      length: 5
  enderman:
    enabled: true
    spell:
      enabled: true
  fish:
    enabled: true
    spell:
      enabled: true

