origins:
  creeper:
    enabled: true
    spell:
      enabled: true
      power: 4
      fire-damage: false
      destroy-blocks: false
  feline:
    enabled: true
    spell:
      enabled: true
  blaze:
    enabled: true
    spell:
      enabled: true

