name: OriginsSpigot
version: '${project.version}'
main: me.isaacbarker.originsspigot.OriginsSpigot
api-version: 1.18
authors: [ G_ja ]
description: An adaptation of the fabric OriginsMC mod on Spigot.
commands:
  origin:
    description: switch origin
    usage: /origin
    permission: originspigot.switch